### ISSUE TITLE
dotenv to remove deploy info from source code

### ISSUE THREAD

**Issue by brunodrugowick** [RebeccaMM/node-api#1]
You can use https://www.npmjs.com/package/dotenv. 

With it you create env vars on a .env file and reference as env vars on your code. On production you can also have an .env var or OS-managed env vars.

https://github.com/RebeccaMM/node-api/blob/2d4ae326e32de13a266b8f24b0be706e2ce14013/server.js#L13

**Comment by RebeccaMM** [comment]
I added the dotenv in my last commit. Piece of cake! Thaks for the suggestion :smiley:
